In [2]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier

In [3]:
hosp_train = pd.read_csv('Datasets/hospitalizaciones_train.csv')
hosp_train.isna().sum()

Available Extra Rooms in Hospital    0
Department                           0
Ward_Facility_Code                   0
doctor_name                          0
staff_available                      0
patientid                            0
Age                                  0
gender                               0
Type of Admission                    0
Severity of Illness                  0
health_conditions                    0
Visitors with Patient                0
Insurance                            0
Admission_Deposit                    0
Stay (in days)                       0
dtype: int64

In [4]:
hosp_train

,Available Extra Rooms in Hospital,Department,Ward_Facility_Code,doctor_name,staff_available,patientid,Age,gender,Type of Admission,Severity of Illness,health_conditions,Visitors with Patient,Insurance,Admission_Deposit,Stay (in days)
0,4,gynecology,D,Dr Sophia,0,33070,41-50,Female,Trauma,Extreme,Diabetes,4,Yes,2966.408696,8
1,4,gynecology,B,Dr Sophia,2,34808,31-40,Female,Trauma,Minor,Heart disease,2,No,3554.835677,9
2,2,gynecology,B,Dr Sophia,8,44577,21-30,Female,Trauma,Extreme,Diabetes,2,Yes,5624.733654,7
3,4,gynecology,D,Dr Olivia,7,3695,31-40,Female,Urgent,Moderate,None,4,No,4814.149231,8
4,2,anesthesia,E,Dr Mark,10,108956,71-80,Male,Trauma,Moderate,Diabetes,2,No,5169.269637,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409995,1,gynecology,D,Dr Sarah,1,63105,31-40,Female,Trauma,Minor,Asthama,3,Yes,3902.291076,8
409996,5,gynecology,D,Dr Nathan,5,129292,21-30,Female,Trauma,Extreme,Other,4,No,4771.995223,9
409997,4,gynecology,D,Dr Sarah,9,11399,21-30,Female,Emergency,Minor,Asthama,4,Yes,3816.994210,9
409998,10,gynecology,D,Dr Olivia,10,75003,21-30,Female,Trauma,Moderate,Other,2,Yes,3841.577491,9
409999,3,gynecology,F,Dr Nathan,0,128183,41-50,Female,Trauma,Minor,Other,8,Yes,4329.046412,8

In [91]:
def transform_column_to_numbers(column):
    col_unique = column.unique()
    result = column.replace(col_unique,np.arange(len(col_unique)))
    return result

In [92]:
ht = hosp_train.copy()
ht_str = ht.select_dtypes(include='object')
ht_str = ht_str.apply(lambda x: transform_column_to_numbers(x))
hosp_train['Stay (in days)'][hosp_train['Stay (in days)']<= 8]= 0
hosp_train['Stay (in days)'][hosp_train['Stay (in days)']> 8]= 1
for i in ht.columns:
    if i in ht_str.columns:
        hosp_train[i] = ht_str[i]

hosp_train

C:\Users\elbue\AppData\Local\Temp\ipykernel_9428\1212543425.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hosp_train['Stay (in days)'][hosp_train['Stay (in days)']<= 8]= 0
C:\Users\elbue\AppData\Local\Temp\ipykernel_9428\1212543425.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hosp_train['Stay (in days)'][hosp_train['Stay (in days)']> 8]= 1

,Available Extra Rooms in Hospital,Department,Ward_Facility_Code,doctor_name,staff_available,patientid,Age,gender,Type of Admission,Severity of Illness,health_conditions,Visitors with Patient,Insurance,Admission_Deposit,Stay (in days)
0,4,0,0,0,0,33070,0,0,0,0,0,4,0,2966.408696,0
1,4,0,1,0,2,34808,1,0,0,1,1,2,1,3554.835677,1
2,2,0,1,0,8,44577,2,0,0,0,0,2,0,5624.733654,0
3,4,0,0,1,7,3695,1,0,1,2,2,4,1,4814.149231,0
4,2,1,2,2,10,108956,3,1,0,2,0,2,1,5169.269637,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409995,1,0,0,4,1,63105,1,0,0,1,4,3,0,3902.291076,0
409996,5,0,0,6,5,129292,2,0,0,0,3,4,1,4771.995223,1
409997,4,0,0,4,9,11399,2,0,2,1,4,4,0,3816.994210,1
409998,10,0,0,1,10,75003,2,0,0,2,3,2,0,3841.577491,1
409999,3,0,3,6,0,128183,0,0,0,1,3,8,0,4329.046412,0

In [93]:
# hosp_test = pd.read_csv('Datasets/hospitalizaciones_test.csv')
# htest = hosp_test.copy()
# htest_str = htest.select_dtypes(include='object')
# htest_str = ht_str.apply(lambda x: transform_column_to_numbers(x))

# for i in ht.columns:
#     if i in htest_str.columns:
#         hosp_test[i] = htest_str[i]
        
# hosp_test

,Available Extra Rooms in Hospital,Department,Ward_Facility_Code,doctor_name,staff_available,patientid,Age,gender,Type of Admission,Severity of Illness,health_conditions,Visitors with Patient,Insurance,Admission_Deposit
0,3,0,0,0,10,2858,0,0,0,0,0,2,0,4749.640225
1,2,0,1,0,4,65657,1,0,0,1,1,2,1,4122.261324
2,2,0,1,0,7,45598,2,0,0,0,0,3,0,5459.067882
3,2,0,0,1,1,31132,1,0,1,2,2,2,1,3987.033318
4,2,1,2,2,7,125021,3,1,0,2,0,2,1,4770.789695
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89995,4,0,0,4,2,43001,4,0,0,1,4,3,0,4105.795901
89996,13,0,3,0,8,85601,1,0,2,2,0,2,0,4631.550257
89997,2,0,0,4,3,22447,2,0,2,2,4,2,0,5456.930075
89998,2,0,3,4,1,29957,2,0,2,1,5,2,0,4694.127772
89999,3,0,3,1,3,45008,2,0,0,2,3,4,0,4713.868519

In [1]:
decision = DecisionTreeClassifier(max_depth = 3, random_state = 42)

x = hosp_train[['Available Extra Rooms in Hospital', 'Department', 'Ward_Facility_Code',
       'doctor_name', 'staff_available', 'patientid', 'Age', 'gender',
       'Type of Admission', 'Severity of Illness', 'health_conditions',
       'Visitors with Patient', 'Insurance', 'Admission_Deposit']]

y= hosp_train['Stay (in days)']

NameError: name 'DecisionTreeClassifier' is not defined

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30, random_state=42)

In [95]:
decision.fit(x_train.values,y_train.values)

DecisionTreeClassifier(max_depth=3, random_state=42)

In [96]:
x_test = hosp_test[['Available Extra Rooms in Hospital', 'Department', 'Ward_Facility_Code',
       'doctor_name', 'staff_available', 'patientid', 'Age', 'gender',
       'Type of Admission', 'Severity of Illness', 'health_conditions',
       'Visitors with Patient', 'Insurance', 'Admission_Deposit']]

In [97]:
print(decision.feature_importances_)

[0.         0.57629952 0.         0.         0.         0.
 0.42370048 0.         0.         0.         0.         0.
 0.         0.        ]

In [98]:
y_pred = decision.predict(x_test.values)
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [99]:
from sklearn.metrics import accuracy_score

accuracy_score(y_train[:90000],y_pred)

0.6863111111111111